<h2 align="center">Elastica simple experiment</h2> 

In [1]:
# Imports
import math as m
import numpy as np
import matplotlib.pyplot as plt
import holoviews as hv
import pylab as pl
from pylab import exp,cos,sin,pi,tan, pi
import pandas as pd
import seaborn as sb
import holoviews as hv
from IPython.display import SVG
import io
from PIL import Image
from random import random
import elastica as el
import elastica_neurons as en
from dynamics import *
%matplotlib inline
hv.notebook_extension()

/afs/inf.ed.ac.uk/user/s12/s1247380/Documents/HonoursProject/Python/venv/lib/python2.7/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)


Horizontal bars, same y, difference in x coordinate

In [7]:
en.E(np.pi/3,np.pi/2,[-1,0])

array([ 7.67635898])

Shouldn't this be 0, as we have two horizontal lines next to each other, which are connected with a straight line?

Vertical bars, same y, difference in x coordinate

In [3]:
en.E(pi/2,pi/2,[1,0])

array([ 9.8696044])

This should be high, as we have two vertical bars, which are connected with long parabola?

Similar to the experiments above..

Horizontal bars, same x, difference in y coordinate

In [4]:
en.E(0,0,[0,1])

array([ 9.8696044])

Vertical bars, same x, difference in y coordinate

In [5]:
en.E(pi/2,pi/2,[0,1])

array([ 0.])

In [6]:
def findE(c,f,X):
    ''' find E, the approximated sharon energy
    Inputs
    ----------
    - c: current bar orientation
    - f: flanker orientation
    - X: relative flanker distance and position orientation         
    '''
    # define x and y 
    x = X[0]
    y = X[1]      
    
    # flanker positional angle
    theta = pl.arctan2(x,y)
    
    # find and return D
    Ba = pl.arctan(tan(0.5*(-f+theta)))*2     
    Bb = pl.arctan(tan(0.5*(c-theta)))*2
    return  4*(Ba**2 + Bb**2 - Ba*Bb)

def E(c,f,X):
    ''' find the direction invariant approximated sharon energy
    Inputs
    ----------
    - c: current bar orientation (can be double or array, if array D returns an array of D values)
    - f: flanker orientation  (double)
    - X: relative flanker distance and position orientation         
    '''
    
    # check if c is an array, and assign length (note, f cannot be array)
    if isinstance(c,pl.ndarray):
        length = len(c)
    else:
        length = 1        
    
    # find D candiates across all directions
    E = pl.zeros((length,4))  
    E[:,0] = findE(c,f,X)
    E[:,1] = findE(c+pi,f,X)
    E[:,2] = findE(c,f+pi,X)
    E[:,3] = findE(c+pi,f+pi,X)
        
    # return the minimum energy
    return E.min(1)